# Generated by Django 4.0.1 on 2022-02-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='public',
        ),
    ]
