# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
