# Generated by Django 4.0.1 on 2022-02-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instant', '0002_alter_channel_level'),
        ('rechat', '0002_remove_chatroom_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='channel',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='instant.channel', verbose_name='Channel'),
        ),
    ]
